<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>SaveMod20XX</RootNamespace>
    <AssemblyName>SaveMod20XX</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Numerics" />
  </ItemGroup>

</Project>
